name: StyleCop Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-checks:
    name: Run StyleCop Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.8.x' # Update based on your project

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project with StyleCop
        run: dotnet build --no-restore --warnaserror

      - name: Run Static Analysis
        run: dotnet build /warnaserror || echo "::error::StyleCop violations found!"
