name: Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!main'

jobs:
  build-and-validate:
    name: Build and Validate (Windows 2022)
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.406

      - name: Restore NuGet packages
        run: dotnet restore ./IsolateElement.sln

      - name: Build with StyleCop validation
        shell: pwsh
        run: |
          dotnet build ./IsolateElement.sln `
            --configuration Release `
            --p:CodeAnalysisTreatWarningsAsErrors=true `
            --p:TreatWarningsAsErrors=true `
            --warnaserror

      - name: Run Nuke build
        run: ./.nuke/build.cmd Compile PublishGitHub --GitHubToken ${{ secrets.GITHUB_TOKEN }}
